version: 0.0
os: linux
files:
  - source: genertator.go
      destination: /home/ec2-user 
hooks:
   BeforeInstall:
   - location: install.sh
     timeout: 600
     runas: root
   ApplicationStart:
   - location: run.sh
     timeout: 300
